# -*- coding: utf-8 -*-
"""SOM - K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPORyn-SOtCnKgCTmRpK8hmmEmcRgERt
"""

!pip install minisom

import minisom
import pandas as pd
import sklearn
import matplotlib

pd.__version__, sklearn.pd__version__, matplotlib.__version__

from minisom import MiniSom
from sklearn.preprocessing import MinMaxScaler
from matplotlib.pylab import pcolor, colorbar, plot

dataset = pd.read_csv('wines.csv')

X = dataset.iloc[:, 1:14].values
y = dataset.iloc[:, 0].values

normalizer = MinMaxScaler(feature_range=(0,1))
X = normalizer.fit_transform(X)

som = MiniSom(x=8, y = 8, input_len = 13, sigma = 1.0, learning_rate=0.5, random_seed = 2)

som.random_weights_init(X)

som.train_random(data = X, num_interarion = 600)

som._weigths.shape

som.activation_map

q = som.activation_response(X)

pcolor(som.distance_map().T)
colorbar()

w.som

som._weigths

w = som.winner(X[0])

markers = ['o', 's', 'D']
color = ['r','g','b']

pcolor(som.distance_map().T)
colorbar()

for i,x in enumerate(X):
  #print(i)
  #print(x)
  w = som.winner(x)
  #print(w)
  plot(w[0] + 0.5,w[1]+ 0.5, markers[y[i]-1], markerfacecolor='None', markeredgecolor=color[y[i]-1], markeredgewidth=2, markersize=10)